### ISSUE TITLE
A question about python_hook_experiment.py (IMAGE_IMPORT_DESCRIPTOR)

### ISSUE THREAD

**Issue by upgradeQ** [aidatorajiro/misc#1]
Hi, sorry to bother you as it seems that this repository is not open for contributions or support requests, but you have a Python script here and on the gist site, so I decided to ask here. 

Did you ever get hook4.py, hook5.py to work? Because it looks like a draft, so I've tried running all three, even the [gist](https://gist.github.com/aidatorajiro/3774a67cbfe4b4d700c38526934f2624), but they don't work( nothing prints to console). Maybe there is a problem with mismatching versions of Python 32/64 bit or 32/64 PC? I've tested them on Windows 11 Home 22H2 64-bit with Python 3.9 64-bit , Python 3.11 32/64bit (embedded version).

**Comment by torahappy** [comment]
thank you for looking my code!Well it's a work-in-progress project (left for many years). Maybe you can print "storage" variable to see what happens, but I'm not sure because I haven't tested it for many years...The aim of project is to understand api hook and make something like very simple version of https://github.com/Modorganizer2/usvfs.2023/07/13 5:39、upgradeQ ***@***.***>のメール:﻿
Hi, sorry to bother you as it seems that this repository is not open for contributions or support requests, but you have a Python script here and on the gist site, so I decided to ask here.
Did you ever get hook4.py, hook5.py to work? Because it looks like a draft, so I've tried running all three, even the gist, but they don't work( nothing prints to console). Maybe there is a problem with mismatching versions of Python 32/64 bit or 32/64 PC? I've tested them on Windows 11 Home 22H2 64-bit with Python 3.9 64-bit , Python 3.11 32/64bit (embedded version).

**Comment by upgradeQ** [comment]
The "storage" variable prints empty dict. I've also found iat hooking [library](https://github.com/hakril/PythonForWindows) for python, it has working [demo](https://hakril.github.io/PythonForWindows/build/html/sample.html#iat-hooking) with `_winreg` module ( you have to change to  `winreg` in Python 3). I've tried to hook `CreateFileW` in current Python proccess in console interpreter mode, but it also doesn't work
```python
import windows
from time import sleep
from windows.hooks import *

G = lambda: ...
G.executions = 0


@CreateFileWCallback
def createfile_callback(
    lpFileName,
    dwDesiredAccess,
    dwShareMode,
    lpSecurityAttributes,
    dwCreationDisposition,
    dwFlagsAndAttributes,
    hTemplateFile,
    real_function,
):
    G.executions += 1
    print("Trying to open {0}".format(lpFileName))
    if "secret" in lpFileName:
        return 0xFFFFFFFF
    return real_function()


peb = windows.current_process.peb
pythondll_module = [
    m for m in peb.modules if m.name.startswith("python") and m.name.endswith(".dll")
][0]
adv_imports = pythondll_module.pe.imports["kernel32.dll"]
iat_create_file = [entry for entry in adv_imports if entry.name == "CreateFileW"][0]
print(iat_create_file)
result = iat_create_file.set_hook(createfile_callback)
with open("secret123.txt", "w") as f:
    f.write("12341234")
    sleep(1)
print(G.executions)
with open("secret.txt", "r") as f:  # needs secret.txt to be present in directory
    print(f.read())
    sleep(1)
print(G.executions)

```
It prints 0 executions and no output of lpFileName.

**Comment by upgradeQ** [comment]
Check out [pyjectify](https://github.com/Petitoto/pyjectify), it is not an IAT hook, but it works.
```python
import pyjectify

# Open mspaint process & inject Python DLL
mspaint = pyjectify.byName("mspaint.exe")[0]
mspaint.pythonlib.python_mod = mspaint.inject.load_library(
    "C:\\c_path\\py_path_location\\python311.dll"
)
mspaint.pythonlib.initialize()

# Step 1: define our new function
pycode = """
import ctypes
from ctypes.wintypes import BOOL, BOOLEAN, LPCWSTR, DWORD, HANDLE
from ctypes.wintypes import WCHAR, USHORT, LPVOID, ULONG, LPDWORD
def CreateFileW(
    a1:LPCWSTR,
    a2:DWORD,
    a3:DWORD,
    a4:LPVOID,
    a5:DWORD,
    a6:DWORD,
    a7:HANDLE, 
) -> HANDLE:
  ctypes.windll.user32.MessageBoxW(0, f"[h] {(a1,a2,a3,a4,a5,a6,a7)}", "Test", 0)
  return o_CreateFileW(a1,a2,a3,a4,a5,a6,a7)
"""

mspaint.pythonlib.exec(pycode)

# Step 2: get original function address and setup a trampoline (of 15 bytes size)
kernel32 = mspaint.process.get_module("kernel32.dll")
oaddr = kernel32.exports["CreateFileW"] + kernel32.base_addr
trampoline_addr = mspaint.hook.trampoline(oaddr, 15)

# Step 3: prepare Python function hooking
hook_addr = mspaint.pythonlib.prepare_hook("CreateFileW", trampoline_addr)

# Step 4: inline hook
mspaint.hook.inline(oaddr, hook_addr)


def p():  # P.S this is a permanent hook, you have to restart process to hook again. sleep for debug purposes
    from time import sleep

    while 1:
        sleep(1)
```
